/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nabil Rizki
 */
public class ProgramAritmatika extends javax.swing.JFrame {
     String jenis = "";
    int jumlah;

    
    /**
     * Creates new form JFrame
     */
       
        
    
    public ProgramAritmatika() {
        initComponents();
        jenis = null;
        
            
        panel.setVisible(false);
        bil1.setVisible(false);
        bil2.setVisible(false);
        bil3.setVisible(false);
        bil4.setVisible(false);
        B1.setVisible(false);
        B2.setVisible(false);
        B3.setVisible(false);
        B4.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JenisAritmatika = new javax.swing.JComboBox<>();
        panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        JumlahBilangan = new javax.swing.JComboBox<>();
        B1 = new javax.swing.JLabel();
        B2 = new javax.swing.JLabel();
        B3 = new javax.swing.JLabel();
        B4 = new javax.swing.JLabel();
        bil1 = new javax.swing.JTextField();
        bil2 = new javax.swing.JTextField();
        bil4 = new javax.swing.JTextField();
        bil3 = new javax.swing.JTextField();
        ButtonHitung = new javax.swing.JButton();
        ket = new javax.swing.JLabel();
        TFHasil = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        JenisAritmatika.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Salah Satu", "Penjumlahan", "Pengurangan", "Perkalian", "Pembagian" }));
        JenisAritmatika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JenisAritmatikaActionPerformed(evt);
            }
        });
        getContentPane().add(JenisAritmatika);
        JenisAritmatika.setBounds(180, 40, 170, 20);

        panel.setBorder(javax.swing.BorderFactory.createTitledBorder("OPERASI"));
        panel.setLayout(null);

        jLabel3.setText("Jumlah Bilangan");
        panel.add(jLabel3);
        jLabel3.setBounds(20, 50, 100, 20);

        JumlahBilangan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));
        JumlahBilangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumlahBilanganActionPerformed(evt);
            }
        });
        panel.add(JumlahBilangan);
        JumlahBilangan.setBounds(170, 50, 170, 20);

        B1.setText("Bilangan 1");
        panel.add(B1);
        B1.setBounds(40, 90, 110, 14);

        B2.setText("Bilangan 2");
        panel.add(B2);
        B2.setBounds(40, 120, 100, 14);

        B3.setText("Bilangan 3");
        panel.add(B3);
        B3.setBounds(40, 150, 90, 14);

        B4.setText("Bilangan 4");
        panel.add(B4);
        B4.setBounds(40, 180, 70, 14);
        panel.add(bil1);
        bil1.setBounds(170, 90, 170, 30);

        bil2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil2ActionPerformed(evt);
            }
        });
        panel.add(bil2);
        bil2.setBounds(170, 120, 170, 30);
        panel.add(bil4);
        bil4.setBounds(170, 180, 170, 30);
        panel.add(bil3);
        bil3.setBounds(170, 150, 170, 30);

        ButtonHitung.setText("Hitung");
        ButtonHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHitungActionPerformed(evt);
            }
        });
        panel.add(ButtonHitung);
        ButtonHitung.setBounds(170, 210, 170, 23);
        panel.add(ket);
        ket.setBounds(20, 20, 90, 30);

        TFHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFHasilActionPerformed(evt);
            }
        });
        panel.add(TFHasil);
        TFHasil.setBounds(170, 260, 170, 70);

        getContentPane().add(panel);
        panel.setBounds(10, 70, 380, 350);

        jLabel2.setText("Jenis Aritmatika");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 40, 100, 20);

        jLabel1.setText("Program Aritmatika");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 10, 120, 30);

        setBounds(0, 0, 416, 468);
    }// </editor-fold>//GEN-END:initComponents

    private void JenisAritmatikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JenisAritmatikaActionPerformed
        // TODO add your handling code here:
        setJenisAritmatika();
    }//GEN-LAST:event_JenisAritmatikaActionPerformed

    private void JumlahBilanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumlahBilanganActionPerformed
        // TODO add your handling code here:
        getJumlah();
    }//GEN-LAST:event_JumlahBilanganActionPerformed

    private void bil2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bil2ActionPerformed

    private void ButtonHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHitungActionPerformed
        // TODO add your handling code here:
        Double hsl = 0.0;
        Double a1, a2, a3, a4;
        a1 = Double.parseDouble(bil1.getText().toString());
        a2 = Double.parseDouble(bil2.getText().toString());

        if(jenis.equals("Penjumlahan")){
            if(jumlah == 2){
                hsl = a1 + a2;
                TFHasil.setText(""+a1 + " + " + a2 + " = " + hsl);
            }

            if(jumlah == 3){
                a3 = Double.parseDouble(bil3.getText().toString());
                hsl = a1 + a2 + a3;
                TFHasil.setText(""+a1 + " + " + a2 + " + " + a3 + " = " + hsl);
            }
            if(jumlah == 4){
                a3 = Double.parseDouble(bil3.getText().toString());
                a4 = Double.parseDouble(bil4.getText().toString());
                hsl = a1 + a2 + a3 + a4;
                TFHasil.setText(""+a1 + " + " + a2 + " + " + a3 + "+" + a4 + " = " + hsl);
            }

        }
        if(jenis.equals("Pengurangan")){
            if(jumlah == 2){
                hsl = a1 - a2;
                TFHasil.setText(""+a1 + " - " + a2 + " = " + hsl);
            }

            if(jumlah == 3){
                a3 = Double.parseDouble(bil3.getText().toString());
                hsl = a1 - a2 - a3;
                TFHasil.setText(""+a1 + " - " + a2 + " - " + a3 + " = " + hsl);
            }
            if(jumlah == 4){
                a3 = Double.parseDouble(bil3.getText().toString());
                a4 = Double.parseDouble(bil4.getText().toString());
                hsl = a1 - a2 - a3 - a4;
                TFHasil.setText(""+a1 + " - " + a2 + " - " + a3 + " - " + a4 + " = " + hsl);
            }

        }

        if(jenis.equals("Perkalian")){
            if(jumlah == 2){
                hsl = a1 * a2;
                TFHasil.setText(""+a1 + " * " + a2 + " = " + hsl);
            }

            if(jumlah == 3){
                a3 = Double.parseDouble(bil3.getText().toString());
                hsl = a1 * a2 * a3;
                TFHasil.setText(""+a1 + " * " + a2 + " * " + a3 + " = " + hsl);
            }
            if(jumlah == 4){
                a3 = Double.parseDouble(bil3.getText().toString());
                a4 = Double.parseDouble(bil3.getText().toString());
                hsl = a1 * a2 * a3 * a4;
                TFHasil.setText(""+a1 + " * " + a2 + " * " + a3 + " * " + a4 + " = " + hsl);
            }

        }

        if(jenis.equals("Pembagian")){
            if(jumlah == 2){
                hsl = a1 / a2;
                TFHasil.setText(""+a1 + " / " + a2 + " = " + hsl);
            }

            if(jumlah == 3){
                a3 = Double.parseDouble(bil3.getText().toString());
                hsl = a1 / a2 / a3;
                TFHasil.setText(""+a1 + " / " + a2 + " / " + a3 + " = " + hsl);
            }
            if(jumlah == 4)
            {
                a3 = Double.parseDouble(bil3.getText().toString());
                a4 = Double.parseDouble(bil4.getText().toString());
                hsl = a1 / a2 / a3 / a4;
                TFHasil.setText(""+a1 + " / "
                    + "" + a2 + " / " + a3 + " / " + a4 + " = " + hsl);
            }

        }

    }//GEN-LAST:event_ButtonHitungActionPerformed

    public void setJenisAritmatika() {
       if (JenisAritmatika.getSelectedItem().equals("Penjumlahan")){
                jenis = "Penjumlahan";
                ket.setText("Penjumlahan");
                panel.setVisible(true);
                JumlahBilangan.setEnabled(true);
            }
        else if (JenisAritmatika.getSelectedItem().equals("Pengurangan")){
                jenis = "Pengurangan";
                ket.setText("Pengurangan");
                panel.setVisible(true);
                JumlahBilangan.setEnabled(true);
            }
        else if (JenisAritmatika.getSelectedItem().equals("Perkalian")){
                jenis = "Perkalian";
                ket.setText("Perkalian");
                panel.setVisible(true);
                JumlahBilangan.setEnabled(true);
            }
        else if (JenisAritmatika.getSelectedItem().equals("Pembagian")){
                jenis = "Pembagian";
                ket.setText("Pembagian");
                panel.setVisible(true);
                JumlahBilangan.setEnabled(true);
            }
        else {
            jenis = null;
            panel.setVisible(false);
        }
    }
    
    public void getJumlah(){
        if (JumlahBilangan.getSelectedItem().equals("2")){
            bil1.setVisible(true);
            bil2.setVisible(true);
            bil3.setVisible(false);
            bil4.setVisible(false);
            B1.setVisible(true);
            B2.setVisible(true);
            B3.setVisible(false);
            B4.setVisible(false);
            jumlah = 2;
        }
        else if(JumlahBilangan.getSelectedItem().equals("3")){
            bil1.setVisible(true);
            bil2.setVisible(true);
            bil3.setVisible(true);
            bil4.setVisible(false);
            B1.setVisible(true);
            B2.setVisible(true);
            B3.setVisible(true);
            B4.setVisible(false);
            jumlah = 3;
        }
        else if(JumlahBilangan.getSelectedItem().equals("4")){
            bil1.setVisible(true);
            bil2.setVisible(true);
            bil3.setVisible(true);
            bil4.setVisible(true);
            B1.setVisible(true);
            B2.setVisible(true);
            B3.setVisible(true);
            B4.setVisible(true);
            jumlah = 4;
        }
        else {
        bil1.setVisible(false);
        bil2.setVisible(false);
        bil3.setVisible(false);
        bil4.setVisible(false);
        B1.setVisible(false);
        B2.setVisible(false);
        B3.setVisible(false);
        B4.setVisible(false);
        
        }
    }
    private void TFHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFHasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFHasilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgramAritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgramAritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgramAritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgramAritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgramAritmatika().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel B1;
    private javax.swing.JLabel B2;
    private javax.swing.JLabel B3;
    private javax.swing.JLabel B4;
    private javax.swing.JButton ButtonHitung;
    private javax.swing.JComboBox<String> JenisAritmatika;
    private javax.swing.JComboBox<String> JumlahBilangan;
    private javax.swing.JTextField TFHasil;
    private javax.swing.JTextField bil1;
    private javax.swing.JTextField bil2;
    private javax.swing.JTextField bil3;
    private javax.swing.JTextField bil4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel ket;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables

}
